#!/bin/bash

echo "🔑 FIREBASE TOKEN SETUP GUIDE"
echo "============================="
echo ""
echo "Follow these steps to get your Firebase CI token:"
echo ""
echo "📋 STEP 1: Generate Firebase CI Token"
echo "--------------------------------------"
echo "Run this command on your LOCAL machine (not here):"
echo ""
echo "  firebase login:ci"
echo ""
echo "📋 STEP 2: Copy the Token"
echo "------------------------"
echo "The command above will give you a token that looks like:"
echo "  1//0abcd1234567890..."
echo ""
echo "📋 STEP 3: Add Token to GitHub Secrets"
echo "--------------------------------------"
echo "1. Go to: https://github.com/whoisd3/Target-Game/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Name: FIREBASE_TOKEN"
echo "4. Value: [paste your token from step 1]"
echo "5. Click 'Add secret'"
echo ""
echo "📋 STEP 4: Push to Deploy"
echo "-------------------------"
echo "After adding the secret, any push to main branch will auto-deploy!"
echo ""
echo "🌐 Your game will be live at: https://target-nexus-game.web.app/"
echo ""
echo "💡 Alternative: Manual Deploy"
echo "-----------------------------"
echo "If you want to deploy manually instead:"
echo "  firebase login"
echo "  firebase deploy --project target-nexus-game"